#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Case: same-name managed DCode --fresh re-onboard keeps the new live route (#6311).
#
# Start from the typed target's stock DCode sandbox (model A), seed its config
# with safe preferences plus stale managed/unsafe data, and re-onboard the same
# name to model B. The live identity, host status, registry, and restored config
# must all agree on B before the remaining DCode runtime checks execute.

set -euo pipefail

SANDBOX_NAME="${SANDBOX_NAME:-${NEMOCLAW_SANDBOX_NAME:-}}"
REPO="${REPO:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)}"
CLI="${NEMOCLAW_CLI_BIN:-${REPO}/bin/nemoclaw.js}"
PREFIX="04-deepagents-code-fresh-reonboard"
PRIMARY_TARGET_MODEL="openai/openai/gpt-5.5"
FALLBACK_TARGET_MODEL="nvidia/nvidia/nemotron-3-ultra"

# shellcheck source=test/e2e/lib/hermetic-compatible-inference.sh
. "$REPO/test/e2e/lib/hermetic-compatible-inference.sh"

cleanup() {
  local status=$?
  nemoclaw_e2e_stop_hermetic_compatible_inference
  return "$status"
}

trap cleanup EXIT

fail() {
  printf '%s: FAIL: %s\n' "$PREFIX" "$1" >&2
  exit 1
}

pass() {
  printf '%s: OK (%s)\n' "$PREFIX" "$1"
}

sandbox_exec() {
  openshell sandbox exec --name "$SANDBOX_NAME" -- bash -c "$1" 2>&1
}

dcode_identity() {
  # Invoke dcode by absolute path: `openshell sandbox exec -- dcode ...` runs
  # without a login shell, so /usr/local/bin is not on PATH and a bare `dcode`
  # resolves to "command not found". The image installs the launcher at
  # /usr/local/bin/dcode (see agents/langchain-deepagents-code/Dockerfile).
  openshell sandbox exec --name "$SANDBOX_NAME" -- /usr/local/bin/dcode identity 2>&1
}

identity_field() {
  local output="$1"
  local field="$2"
  printf '%s\n' "$output" | sed -n "s/^${field}:[[:space:]]*//p" | tail -n1
}

assert_identity() {
  local output="$1"
  local model="$2"
  local phase="$3"
  local route provider observed_model endpoint
  route="$(identity_field "$output" Route)"
  provider="$(identity_field "$output" Provider)"
  observed_model="$(identity_field "$output" Model)"
  endpoint="$(identity_field "$output" Endpoint)"
  [ "$route" = "inference" ] || fail "$phase identity route is '${route:-missing}'"
  [ "$provider" = "compatible-endpoint" ] || fail "$phase identity provider is '${provider:-missing}'"
  [ "$observed_model" = "openai:${model}" ] || fail "$phase identity model is '${observed_model:-missing}'"
  [ "$endpoint" = "https://inference.local/v1" ] || fail "$phase identity endpoint is '${endpoint:-missing}'"
}

encode_source() {
  base64 | tr -d '\n'
}

shell_quote() {
  printf "%s" "$1" | sed "s/'/'\\\\''/g; 1s/^/'/; \$s/\$/'/"
}

seed_config_source() {
  cat <<'PY'
import os
from pathlib import Path
import sys
import tomllib
import tomli_w

path = Path("/sandbox/.deepagents/config.toml")
model = sys.argv[1]
config = tomllib.loads(path.read_text(encoding="utf-8"))
provider = config["models"]["providers"]["openai"]
config["models"]["default"] = f"openai:{model}"
provider["models"] = [model]
provider["base_url"] = "https://stale.invalid/v1"
config["update"] = {"check": True, "auto_update": True}
config["ui"] = {"show_scrollbar": True, "show_url_open_toast": False, "theme": "discard"}
config["threads"] = {
    "relative_time": False,
    "sort_order": "created_at",
    "columns": {"initial_prompt": False},
}
config["agents"] = {"startup_command": "discard"}
config["headers"] = {"authorization": "discard"}
config["hooks"] = {"post_start": "discard"}
config["mcp"] = {"autoload": True, "config": "/sandbox/discard-mcp.json"}
config["servers"] = {"discard": {"api_key": "discard"}}
config["shell"] = {"allow_list": ["all"]}
config["skills"] = {"autoload": True, "extra_allowed_dirs": ["/etc"]}
config["tracing"] = {"api_key": "discard"}
headers = (
    "# Generated by NemoClaw. This file contains no provider secrets.\n"
    "# NemoClaw provider route: anthropic; upstream provider: "
    "compatible-anthropic-endpoint; API: anthropic-messages."
)
path.write_text(headers + "\n\n" + tomli_w.dumps(config), encoding="utf-8")
os.chmod(path, 0o600)
print("NEMOCLAW_DCODE_STALE_CONFIG_SEEDED")
PY
}

verify_config_source() {
  cat <<'PY'
from pathlib import Path
import sys
import tomllib

path = Path("/sandbox/.deepagents/config.toml")
initial_model, target_model = sys.argv[1:]
text = path.read_text(encoding="utf-8")
config = tomllib.loads(text)
provider = config["models"]["providers"]["openai"]
assert set(config) == {"models", "update", "ui", "threads"}
assert config["models"]["default"] == f"openai:{target_model}"
assert provider["models"] == [target_model]
assert provider["api_key_env"] == "DEEPAGENTS_CODE_OPENAI_API_KEY"
assert provider["base_url"] == "https://inference.local/v1"
assert config["update"] == {"check": False, "auto_update": False}
assert config["ui"] == {"show_scrollbar": True, "show_url_open_toast": False}
assert config["threads"] == {"relative_time": False, "sort_order": "created_at"}
assert initial_model not in text
for forbidden in (
    "compatible-anthropic-endpoint",
    "https://stale.invalid/v1",
    "startup_command",
    "authorization",
    "autoload",
    "allow_list",
):
    assert forbidden not in text
print("NEMOCLAW_DCODE_FRESH_CONFIG_VERIFIED")
PY
}

[ -n "$SANDBOX_NAME" ] || fail "sandbox name is required"

# The generic cloud-onboard target runs every shared check against its OpenClaw
# sandbox. Typed DCode targets reject this SKIP through their required-check
# wrapper, so this guard only prevents cross-agent execution in the shared run.
if ! sandbox_exec "test -d /sandbox/.deepagents && command -v dcode >/dev/null 2>&1" >/dev/null; then
  printf '%s: SKIP: sandbox %q is not a Deep Agents Code sandbox\n' "$PREFIX" "$SANDBOX_NAME"
  exit 0
fi

[ -x "$CLI" ] || fail "NemoClaw CLI is not executable at $CLI"

if ! identity_before="$(dcode_identity)"; then
  # Surface the captured stdout+stderr (dcode_identity redirects 2>&1) before
  # failing. Without this the real reason `dcode identity` exits non-zero is
  # discarded and CI/result.json only show the generic message with stdout "".
  printf '%s: diagnostic: initial dcode identity output:\n%s\n' "$PREFIX" "${identity_before:-<no output captured>}"
  fail "could not read initial dcode identity"
fi
model_a="$(identity_field "$identity_before" Model)"
model_a="${model_a#openai:}"
[ -n "$model_a" ] || fail "initial dcode identity did not report a model"
assert_identity "$identity_before" "$model_a" "initial"

if [ "$model_a" = "$PRIMARY_TARGET_MODEL" ]; then
  model_b="$FALLBACK_TARGET_MODEL"
else
  model_b="$PRIMARY_TARGET_MODEL"
fi
[ "$model_a" != "$model_b" ] || fail "model A and model B must differ"
pass "initial live identity reports model A"

export NEMOCLAW_E2E_COMPATIBLE_MODEL="$model_b"
if ! nemoclaw_e2e_start_hermetic_compatible_inference; then
  fail "could not start hermetic compatible inference"
fi
pass "started hermetic compatible inference for re-onboard"

seed_source="$(seed_config_source | encode_source)"
seed_command="printf '%s' $(shell_quote "$seed_source") | base64 -d | /opt/venv/bin/python3 -I - $(shell_quote "$model_a")"
seed_output="$(sandbox_exec "$seed_command")" || fail "could not seed stale DCode config"
printf '%s\n' "$seed_output" | grep -Fq "NEMOCLAW_DCODE_STALE_CONFIG_SEEDED" || fail "stale config seed marker is missing"
pass "seeded safe preferences and stale managed data"

if ! reonboard_output="$(
  COMPATIBLE_API_KEY="$COMPATIBLE_API_KEY" \
    NEMOCLAW_ACCEPT_THIRD_PARTY_SOFTWARE=1 \
    NEMOCLAW_AGENT=langchain-deepagents-code \
    NEMOCLAW_COMPAT_MODEL="$model_b" \
    NEMOCLAW_ENDPOINT_URL="$NEMOCLAW_ENDPOINT_URL" \
    NEMOCLAW_MODEL="$model_b" \
    NEMOCLAW_NON_INTERACTIVE=1 \
    NEMOCLAW_PREFERRED_API=openai-completions \
    NEMOCLAW_PROVIDER=custom \
    NEMOCLAW_SANDBOX_NAME="$SANDBOX_NAME" \
    OPENSHELL_GATEWAY=nemoclaw \
    "$CLI" onboard --agent langchain-deepagents-code --name "$SANDBOX_NAME" \
    --fresh --non-interactive --observability --yes --yes-i-accept-third-party-software 2>&1
)"; then
  fail "same-name --fresh re-onboard failed: $reonboard_output"
fi
printf '%s\n' "$reonboard_output" | grep -Fq "Backing up workspace state before recreating sandbox..." || fail "re-onboard did not take the pre-recreate backup path"
printf '%s\n' "$reonboard_output" | grep -Fq "Restoring workspace state from pre-recreate backup..." || fail "re-onboard did not take the restore path"
nemoclaw_e2e_assert_hermetic_compatible_inference_used || fail "re-onboard did not use the hermetic compatible endpoint"
pass "same-name --fresh re-onboard crossed backup and restore boundaries"

sandbox_list="$(openshell sandbox list 2>&1)" || fail "could not list sandbox after re-onboard"
printf '%s\n' "$sandbox_list" | awk -v name="$SANDBOX_NAME" '$1 == name && /Ready/ { found = 1 } END { exit(found ? 0 : 1) }' || fail "same-name sandbox is not Ready after re-onboard"

if ! identity_after="$(dcode_identity)"; then
  printf '%s: diagnostic: dcode identity output after re-onboard:\n%s\n' "$PREFIX" "${identity_after:-<no output captured>}"
  fail "could not read dcode identity after re-onboard"
fi
assert_identity "$identity_after" "$model_b" "fresh"
printf '%s\n' "$identity_after" | grep -Fq "$model_a" && fail "fresh identity still contains model A"
pass "live dcode identity reports model B"

status_json="$("$CLI" "$SANDBOX_NAME" status --json 2>&1)" || fail "nemoclaw status failed after re-onboard"
STATUS_JSON="$status_json" SANDBOX_NAME="$SANDBOX_NAME" MODEL_B="$model_b" node -e '
const status = JSON.parse(process.env.STATUS_JSON);
if (status.name !== process.env.SANDBOX_NAME ||
    status.model !== process.env.MODEL_B ||
    status.provider !== "compatible-endpoint") process.exit(1);
' || fail "nemoclaw status does not report model B and compatible-endpoint"

SANDBOX_NAME="$SANDBOX_NAME" MODEL_B="$model_b" node -e '
const fs = require("node:fs");
const path = require("node:path");
const registry = JSON.parse(fs.readFileSync(path.join(process.env.HOME, ".nemoclaw", "sandboxes.json"), "utf8"));
const entry = registry.sandboxes?.[process.env.SANDBOX_NAME];
if (!entry || entry.agent !== "langchain-deepagents-code" ||
    entry.model !== process.env.MODEL_B ||
    entry.provider !== "compatible-endpoint" ||
    entry.credentialEnv !== "COMPATIBLE_API_KEY") process.exit(1);
' || fail "host registry does not report the verified model B selection"
pass "status and registry report model B"

verify_source="$(verify_config_source | encode_source)"
verify_command="printf '%s' $(shell_quote "$verify_source") | base64 -d | /opt/venv/bin/python3 -I - $(shell_quote "$model_a") $(shell_quote "$model_b")"
verify_output="$(sandbox_exec "$verify_command")" || fail "live DCode config does not preserve the managed restore boundary"
printf '%s\n' "$verify_output" | grep -Fq "NEMOCLAW_DCODE_FRESH_CONFIG_VERIFIED" || fail "fresh config verification marker is missing"
pass "config keeps model B and only the allowlisted preferences"

printf '%s: 6 passed, 0 failed\n' "$PREFIX"
